// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

func (User) IsEntity() {}
