docker_compose("./docker-compose.yml", project_name="hackathon-x")

local_resource("react-frontend",
  allow_parallel=True,
  serve_cmd="cd ../react-frontend; make run",
  labels="frontend",
  links=[
    link("http://localhost:3000", "Frontend"),
    link("http://localhost:3000/sandbox", "GraphQL Sandbox"),
  ],
)
local_resource("generate-graphql-types",
  serve_cmd="cd ../react-frontend; make watch-codegen",
  labels="frontend",
)

dc_resource("database", labels="storage")
dc_resource("redis", labels="storage")

dc_resource("backend-a", labels="backend")
dc_resource("backend-b", labels="backend")
dc_resource("gateway", labels="backend")

dc_resource("jaeger", labels="telemetry")
dc_resource("otel-collector", labels="telemetry")
dc_resource("prometheus", labels="telemetry")
